version: "3"
services:
  reverse-proxy:
    image: traefik
    command: --api --docker
    environment:
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
    expose:
      - "8080"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
    restart: on-failure
    labels:
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:monitor.lukas-coding.us"
  manager:
    image: portainer/portainer
    expose:
      - "9000"
    volumes:
      - ./portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    labels:
      - "traefik.port=9000"
      - "traefik.frontend.rule=Host:manager.lukas-coding.us"
  ci:
    build:
      context: ./dockerfiles
      dockerfile: jenkins.Dockerfile
    image: lherman/jenkins
    expose:
      - "8080"
    volumes:
      - ./jenkins:/root/.jenkins
    restart: on-failure
    labels:
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:ci.lukas-coding.us"
  storage:
    image: nextcloud
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_HOST=db 
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
    expose:
      - "80"
    volumes:
      - ./nextcloud:/var/www/html
    restart: on-failure
    labels:
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:storage.lukas-coding.us"

  db:
    image: mariadb
    restart: on-failure
    expose:
      - "3306"
    volumes:
      - ./postgres:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD} 
      - MYSQL_DATABASE=nextcloud

  ocr:
    image: lherman/ocr
    restart: on-failure
    expose:
      - "8080"
    labels:
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:ocr.lukas-coding.us"

  review:
    image: lherman/review
    restart: on-failure
    expose:
      - "8000"
    labels:
      - "traefik.port=8000"
      - "traefik.frontend.rule=Host:review.lukas-coding.us"
